spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/pass_local?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&connectTimeout=2000&serverTimezone=Asia/Seoul
    username: pass_local_user
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20

  batch:
    jdbc:
      initialize-schema: always

kakaotalk:
  host: https://kapi.kakao.com
  token: {YOUR_ACCESS_TOKEN}